package aedifex.display;

import aedifex.build.ProjectSpec;
import aedifex.build.ProjectSpec.LibrarySpec;
import aedifex.build.internal.ProjectResolver;
import aedifex.config.Loader;
import haxe.io.Path;
import sys.FileSystem;
import sys.io.File;

class DisplayTools {
	public static inline final SUPPORT_DIR = ".aedifex";
	public static inline final SUPPORT_HXML = ".aedifex/aedifex.display.hxml";
	public static inline final SUPPORT_MAIN = ".aedifex/AedifexDisplayMain.hx";
	private static inline final GENERATED_LABEL = "generated by aedifex display sync";
	private static inline final IMPLICIT_TOOL_HAXELIB = "aedifex";

	public static function sync(projectRoot:String):DisplayConfigResult {
		var normalizedRoot = Path.normalize(projectRoot);
		var project = Loader.loadProject(normalizedRoot);
		var resolved = ProjectResolver.resolve(project);

		ensureDir(Path.join([normalizedRoot, SUPPORT_DIR]));
		writeIfChanged(Path.join([normalizedRoot, SUPPORT_MAIN]), buildDisplayMainSource());
		writeIfChanged(Path.join([normalizedRoot, SUPPORT_HXML]), buildSupportHxml(normalizedRoot, resolved));

		return {
			label: "Aedifex Root",
			projectRoot: normalizedRoot,
			hxmlPath: Path.join([normalizedRoot, SUPPORT_HXML]),
			args: [Path.join([normalizedRoot, SUPPORT_HXML])],
			files: ["Aedifex.hx", "ProjectDefines.hx"],
			supportFiles: [
				Path.join([normalizedRoot, SUPPORT_MAIN]),
				Path.join([normalizedRoot, SUPPORT_HXML])
			]
		};
	}

	private static function buildDisplayMainSource():String {
		return 'class AedifexDisplayMain {\n'
			+ '\tstatic function main():Void {\n'
			+ '\t\tvar project = Aedifex.project;\n'
			+ '\t\tif (project == null) {\n'
			+ '\t\t\tthrow "Aedifex.project must not be null.";\n'
			+ '\t\t}\n'
			+ '\t}\n'
			+ '}\n';
	}

	private static function buildSupportHxml(projectRoot:String, project:ProjectSpec):String {
		var supportRoot = Path.join([projectRoot, SUPPORT_DIR]);
		var lines:Array<String> = [
			"# " + GENERATED_LABEL,
			"--no-output",
			"-main AedifexDisplayMain",
			"-cp",
			normalizePath(projectRoot),
			"-cp",
			normalizePath(supportRoot)
		];
		appendPair(lines, "-lib", IMPLICIT_TOOL_HAXELIB);

		for (source in project.sources) {
			if (source == null || source.length == 0) continue;
			appendPair(lines, "-cp", resolveProjectPath(projectRoot, source));
		}

		for (library in project.libraries) {
			appendLibrary(lines, projectRoot, library);
		}

		return lines.join("\n") + "\n";
	}

	private static function appendLibrary(lines:Array<String>, projectRoot:String, library:LibrarySpec):Void {
		if (library == null) return;
		if (library.path != null && library.path.length > 0) {
			appendPair(lines, "-cp", resolveProjectPath(projectRoot, library.path));
		}
		if (library.name != null && library.name.length > 0) {
			appendPair(lines, "-lib", library.name);
		}
	}

	private static function appendPair(lines:Array<String>, flag:String, value:String):Void {
		if (value == null || value.length == 0) return;
		lines.push(flag);
		lines.push(value);
	}

	private static function resolveProjectPath(projectRoot:String, value:String):String {
		var normalized = Path.normalize(value);
		if (!Path.isAbsolute(normalized)) {
			normalized = Path.join([projectRoot, normalized]);
		}
		return normalizePath(normalized);
	}

	private static function normalizePath(value:String):String {
		return StringTools.replace(Path.normalize(value), "\\", "/");
	}

	private static function isImplicitToolDependency(name:String):Bool {
		return name != null && name.toLowerCase() == IMPLICIT_TOOL_HAXELIB;
	}

	private static function writeIfChanged(path:String, content:String):Void {
		var existing = try File.getContent(path) catch (_:Dynamic) null;
		if (existing == content) return;
		File.saveContent(path, content);
	}

	private static function ensureDir(path:String):Void {
		if (path == null || path.length == 0 || FileSystem.exists(path)) return;
		var parent = Path.directory(path);
		if (parent != null && parent != "" && parent != path) {
			ensureDir(parent);
		}
		FileSystem.createDirectory(path);
	}
}

typedef DisplayConfigResult = {
	var label:String;
	var projectRoot:String;
	var hxmlPath:String;
	var args:Array<String>;
	var files:Array<String>;
	var supportFiles:Array<String>;
}
