package aedifex.display;

import aedifex.build.BuildArchitecture;
import aedifex.build.BuildPlatform;
import aedifex.build.BuildTarget;
import aedifex.build.Define;
import aedifex.build.Profile;
import aedifex.build.ProjectSpec;
import aedifex.build.ProjectSpec.HaxeFlag;
import aedifex.build.ProjectSpec.LibrarySpec;
import aedifex.build._internal.ExecutionPlanner;
import aedifex.build._internal.ProjectResolver;
import aedifex.config.Loader;
import haxe.Json;
import haxe.io.Path;
import sys.FileSystem;
import sys.io.File;

class DisplayTools {
	public static inline final SUPPORT_DIR = ".aedifex";
	public static inline final LEGACY_SUPPORT_HXML = ".aedifex/aedifex.display.hxml";
	public static inline final LEGACY_SUPPORT_MAIN = ".aedifex/AedifexDisplayMain.hx";
	public static inline final APP_SUPPORT_HXML = ".aedifex/aedifex.app.display.hxml";
	public static inline final APP_SUPPORT_MAIN = ".aedifex/AedifexAppDisplayMain.hx";
	public static inline final ROOT_SUPPORT_HXML = ".aedifex/aedifex.root.display.hxml";
	public static inline final ROOT_SUPPORT_MAIN = ".aedifex/AedifexRootDisplayMain.hx";
	private static inline final GENERATED_LABEL = "generated by aedifex display sync";
	private static inline final IMPLICIT_TOOL_HAXELIB = "aedifex";
	private static final APP_LIBRARY_EXCLUSIONS:Array<String> = [
		"aedifex",
		"aedifex-lime-extension",
		"aedifex-graphaxe-extension"
	];

	public static function sync(projectRoot:String):DisplayConfigResult {
		var normalizedRoot = Path.normalize(projectRoot);
		var rawProject = Loader.loadProject(normalizedRoot);
		var target = ExecutionPlanner.defaultTarget(rawProject);
		var platform = target != null ? ExecutionPlanner.defaultPlatform(rawProject, target) : null;
		var architecture = target != null ? ExecutionPlanner.defaultArchitecture(rawProject, target, platform) : null;
		var profile = ExecutionPlanner.defaultProfile(rawProject);
		var appProject = ProjectResolver.resolve(rawProject, target, platform, architecture, profile);
		var rootProject = ProjectResolver.resolve(rawProject);

		ensureDir(Path.join([normalizedRoot, SUPPORT_DIR]));
		deleteIfExists(Path.join([normalizedRoot, LEGACY_SUPPORT_MAIN]));
		deleteIfExists(Path.join([normalizedRoot, LEGACY_SUPPORT_HXML]));
		writeIfChanged(Path.join([normalizedRoot, APP_SUPPORT_MAIN]), buildDisplayMainSource("AedifexAppDisplayMain"));
		writeIfChanged(Path.join([normalizedRoot, ROOT_SUPPORT_MAIN]), buildDisplayMainSource("AedifexRootDisplayMain"));
		writeIfChanged(
			Path.join([normalizedRoot, APP_SUPPORT_HXML]),
			buildSupportHxml(normalizedRoot, "AedifexAppDisplayMain", appProject, target, platform, architecture, profile, true, false, APP_LIBRARY_EXCLUSIONS)
		);
		writeIfChanged(
			Path.join([normalizedRoot, ROOT_SUPPORT_HXML]),
			buildSupportHxml(normalizedRoot, "AedifexRootDisplayMain", rootProject, null, null, null, null, false, true, [])
		);

		var configs = [
			buildConfigEntry("Aedifex App", normalizedRoot, APP_SUPPORT_HXML, [
				"src/**/*.hx",
				".graphaxe/generated/**/*.hx"
			]),
			buildConfigEntry("Aedifex Root", normalizedRoot, ROOT_SUPPORT_HXML, [
				"Aedifex.hx",
				"ProjectDefines.hx",
				".aedifex/**/*.hx"
			])
		];
		var primary = configs[0];

		return {
			label: primary.label,
			projectRoot: normalizedRoot,
			hxmlPath: primary.hxmlPath,
			args: primary.args,
			files: primary.files,
			configs: configs,
			supportFiles: [
				Path.join([normalizedRoot, APP_SUPPORT_MAIN]),
				Path.join([normalizedRoot, ROOT_SUPPORT_MAIN]),
				Path.join([normalizedRoot, APP_SUPPORT_HXML]),
				Path.join([normalizedRoot, ROOT_SUPPORT_HXML])
			]
		};
	}

	private static function buildConfigEntry(label:String, projectRoot:String, relativeHxmlPath:String, files:Array<String>):DisplayConfigEntry {
		var absoluteHxmlPath = Path.join([projectRoot, relativeHxmlPath]);
		return {
			label: label,
			hxmlPath: absoluteHxmlPath,
			args: [absoluteHxmlPath],
			files: files
		};
	}

	private static function buildDisplayMainSource(className:String):String {
		return 'class ' + className + ' {\n'
			+ '\tstatic function main():Void {}\n'
			+ '}\n';
	}

	private static function buildSupportHxml(
		projectRoot:String,
		mainClass:String,
		project:ProjectSpec,
		?target:BuildTarget,
		?platform:BuildPlatform,
		?architecture:BuildArchitecture,
		?profile:Profile,
		includeTargetContext:Bool = false,
		includeImplicitToolLib:Bool = true,
		?excludedLibraries:Array<String>
	):String {
		var supportRoot = Path.join([projectRoot, SUPPORT_DIR]);
		var lines:Array<String> = [
			"# " + GENERATED_LABEL,
			"--no-output",
			"-main " + mainClass,
			"-cp",
			normalizePath(projectRoot),
			"-cp",
			normalizePath(supportRoot)
		];
		if (includeTargetContext) {
			appendActiveTargetContext(lines, projectRoot, target, platform, architecture, profile);
		}
		if (includeImplicitToolLib) {
			appendPair(lines, "-lib", IMPLICIT_TOOL_HAXELIB);
		}
		for (library in collectProjectLibraries(projectRoot, excludedLibraries)) {
			if (isImplicitToolDependency(library) || isExcludedLibrary(library, excludedLibraries)) continue;
			appendPair(lines, "-lib", library);
		}

		for (source in project.sources) {
			if (source == null || source.length == 0) continue;
			appendPair(lines, "-cp", resolveProjectPath(projectRoot, source));
		}

		appendGeneratedSourceRoots(lines, projectRoot);
		appendDefines(lines, project.defines);
		appendFlags(lines, project.haxeflags);

		for (library in project.libraries) {
			appendLibrary(lines, projectRoot, library, excludedLibraries);
		}

		return lines.join("\n") + "\n";
	}

	private static function appendGeneratedSourceRoots(lines:Array<String>, projectRoot:String):Void {
		var graphaxeGenerated = Path.join([projectRoot, ".graphaxe", "generated"]);
		if (FileSystem.exists(graphaxeGenerated) && FileSystem.isDirectory(graphaxeGenerated)) {
			appendPair(lines, "-cp", normalizePath(graphaxeGenerated));
		}
	}

	private static function appendActiveTargetContext(
		lines:Array<String>,
		projectRoot:String,
		?target:BuildTarget,
		?platform:BuildPlatform,
		?architecture:BuildArchitecture,
		?profile:Profile
	):Void {
		appendTargetFlag(lines, projectRoot, target);
		appendTokenDefine(lines, platform != null ? Std.string(platform) : null);
		appendTokenDefine(lines, architecture != null ? Std.string(architecture) : null);
		appendTokenDefine(lines, profile != null ? Std.string(profile) : null);
	}

	private static function appendDefines(lines:Array<String>, defines:Array<Define>):Void {
		for (define in (defines != null ? defines : [])) {
			if (define == null || define.name == null || StringTools.trim(define.name).length == 0) continue;
			appendPair(lines, "-D", define.value != null && StringTools.trim(define.value).length > 0
				? define.name + "=" + define.value
				: define.name);
		}
	}

	private static function appendFlags(lines:Array<String>, flags:Array<HaxeFlag>):Void {
		for (flag in (flags != null ? flags : [])) {
			if (flag == null || flag.name == null || StringTools.trim(flag.name).length == 0) continue;
			appendPair(lines, flag.name, flag.value != null && StringTools.trim(flag.value).length > 0 ? flag.value : null);
		}
	}

	private static function appendTokenDefine(lines:Array<String>, value:String):Void {
		if (value == null || StringTools.trim(value).length == 0) {
			return;
		}
		appendPair(lines, "-D", StringTools.trim(value));
	}

	private static function appendTargetFlag(lines:Array<String>, projectRoot:String, target:BuildTarget):Void {
		if (target == null) {
			return;
		}

		var supportRoot = Path.join([projectRoot, SUPPORT_DIR]);
		switch (target) {
			case BuildTarget.JS:
				appendPair(lines, "-js", normalizePath(Path.join([supportRoot, ".display.js"])));
			case BuildTarget.CPP:
				appendPair(lines, "-cpp", normalizePath(Path.join([supportRoot, ".display-cpp"])));
			case BuildTarget.HL:
				appendPair(lines, "-hl", normalizePath(Path.join([supportRoot, ".display.hl"])));
			case BuildTarget.NEKO:
				appendPair(lines, "-neko", normalizePath(Path.join([supportRoot, ".display.n"])));
			case BuildTarget.JVM:
				appendPair(lines, "-java", normalizePath(Path.join([supportRoot, ".display-java"])));
			case BuildTarget.PHP:
				appendPair(lines, "-php", normalizePath(Path.join([supportRoot, ".display-php"])));
		}
	}

	private static function collectProjectLibraries(projectRoot:String, ?excludedLibraries:Array<String>):Array<String> {
		var results:Array<String> = [];
		var haxelibPath = Path.join([projectRoot, "haxelib.json"]);
		if (!FileSystem.exists(haxelibPath) || FileSystem.isDirectory(haxelibPath)) {
			return results;
		}

		try {
			var data:Dynamic = Json.parse(File.getContent(haxelibPath));
			var dependencies:Dynamic = Reflect.field(data, "dependencies");
			if (dependencies == null) {
				return results;
			}

			for (field in Reflect.fields(dependencies)) {
				if (field == null) continue;
				var normalized = StringTools.trim(field);
				if (normalized.length == 0) continue;
				if (isExcludedLibrary(normalized, excludedLibraries)) continue;
				if (results.indexOf(normalized) >= 0) continue;
				results.push(normalized);
			}
		} catch (_:Dynamic) {}

		return results;
	}

	private static function appendLibrary(lines:Array<String>, projectRoot:String, library:LibrarySpec, ?excludedLibraries:Array<String>):Void {
		if (library == null) return;
		if (library.name != null && isExcludedLibrary(library.name, excludedLibraries)) return;
		if (library.path != null && library.path.length > 0) {
			appendPair(lines, "-cp", resolveProjectPath(projectRoot, library.path));
		}
		if (library.name != null && library.name.length > 0) {
			appendPair(lines, "-lib", library.name);
		}
	}

	private static function appendPair(lines:Array<String>, flag:String, value:String):Void {
		if (value == null || value.length == 0) return;
		lines.push(flag);
		lines.push(value);
	}

	private static function resolveProjectPath(projectRoot:String, value:String):String {
		var normalized = Path.normalize(value);
		if (!Path.isAbsolute(normalized)) {
			normalized = Path.join([projectRoot, normalized]);
		}
		return normalizePath(normalized);
	}

	private static function normalizePath(value:String):String {
		return StringTools.replace(Path.normalize(value), "\\", "/");
	}

	private static function isImplicitToolDependency(name:String):Bool {
		return name != null && name.toLowerCase() == IMPLICIT_TOOL_HAXELIB;
	}

	private static function writeIfChanged(path:String, content:String):Void {
		var existing = try File.getContent(path) catch (_:Dynamic) null;
		if (existing == content) return;
		File.saveContent(path, content);
	}

	private static function isExcludedLibrary(name:String, ?excludedLibraries:Array<String>):Bool {
		if (name == null) return false;
		var normalized = StringTools.trim(name).toLowerCase();
		for (candidate in (excludedLibraries != null ? excludedLibraries : [])) {
			if (candidate != null && normalized == StringTools.trim(candidate).toLowerCase()) {
				return true;
			}
		}
		return false;
	}

	private static function appendUnique(values:Array<String>, value:String):Void {
		if (value == null || value.length == 0 || values.indexOf(value) >= 0) {
			return;
		}
		values.push(value);
	}

	private static function deleteIfExists(path:String):Void {
		if (path == null || path.length == 0 || !FileSystem.exists(path) || FileSystem.isDirectory(path)) {
			return;
		}
		FileSystem.deleteFile(path);
	}

	private static function ensureDir(path:String):Void {
		if (path == null || path.length == 0 || FileSystem.exists(path)) return;
		var parent = Path.directory(path);
		if (parent != null && parent != "" && parent != path) {
			ensureDir(parent);
		}
		FileSystem.createDirectory(path);
	}
}

typedef DisplayConfigResult = {
	var label:String;
	var projectRoot:String;
	var hxmlPath:String;
	var args:Array<String>;
	var files:Array<String>;
	var configs:Array<DisplayConfigEntry>;
	var supportFiles:Array<String>;
}

typedef DisplayConfigEntry = {
	var label:String;
	var hxmlPath:String;
	var args:Array<String>;
	var files:Array<String>;
}
